### ISSUE TITLE
[Bug]: new 1.11.0 version fails to connect to Signal

### ISSUE THREAD

**Issue by stuartlangridge** [snapcrafters/signal-desktop#203]
### What happened?

I closed down the previous version of Signal, which was happily connected to the servers (and was installed from the snap), and I refreshed Signal Desktop to the latest version from the snap, and this latest version does not connect. The UI says "Something went wrong! Failed to connect to server." In the terminal, output contains this repeatedly:

```
{"name":"log","hostname":"oz","pid":151226,"level":30,"msg":"opening provisioning socket https://textsecure-service.whispersystems.org","time":"2023-11-23T12:05:01.451Z","v":0}
{"name":"log","hostname":"oz","pid":151226,"level":30,"msg":"provisioning socket closed 1006","time":"2023-11-23T12:05:02.432Z","v":0}
{"name":"log","hostname":"oz","pid":151226,"level":30,"msg":"provisioning failed Error: websocket closed\n    at W3CWebSocket.socket.onclose (file://[REDACTED]/app.asar/js/libtextsecure.js:38094:22)\n    at W3CWebSocket._dispatchEvent [as dispatchEvent] ([REDACTED]/app.asar/node_modules/yaeti/lib/EventTarget.js:107:17)\n    at W3CWebSocket.onConnectFailed ([REDACTED]/app.asar/node_modules/websocket/lib/W3CWebSocket.js:219:14)\n    at WebSocketClient.<anonymous> ([REDACTED]/app.asar/node_modules/websocket/lib/W3CWebSocket.js:59:25)\n    at emitOne (events.js:115:13)\n    at WebSocketClient.emit (events.js:210:7)\n    at ClientRequest.handleRequestError ([REDACTED]/app.asar/node_modules/websocket/lib/WebSocketClient.js:215:14)\n    at emitOne (events.js:115:13)\n    at ClientRequest.emit (events.js:210:7)\n    at TLSSocket.socketErrorListener (_http_client.js:401:9)","time":"2023-11-23T12:05:02.432Z","v":0}
```

which seems relevant.

### What should have happened?

the new 1.11.0 version should have worked, as the previous (up to date) version I was running did ten seconds previously!

### Output of `snap info $snap_name`

```shell
12:02 ~ $ snap info signal-desktop
name:      signal-desktop
summary:   Speak Freely - Private Messenger
publisher: Snapcrafters✪
store-url: https://snapcraft.io/signal-desktop
contact:   https://github.com//snapcrafters/signal-desktop/issues
license:   unset
description: |
  **Note: To use the Signal desktop app, you must first install Signal on
  your phone.**
  
  Millions of people use Signal every day for free and instantaneous
  communication anywhere in the world. Send and receive high-fidelity
  messages, participate in HD voice/video calls, and explore a growing set of
  new features that help you stay connected. Signal's advanced
  privacy-preserving technology is always enabled, so you can focus on
  sharing the moments that matter with the people who matter to you.
  
  - Say anything - State-of-the-art end-to-end encryption (powered by the
  open source Signal Protocol™) keeps your conversations secure. Privacy
  isn't an optional mode; it's just the way that Signal works. Every message,
  every call, every time.
  - Go fast - Messages are delivered quickly and reliably, even on slow
  networks. Signal is optimized to operate in the most constrained
  environment possible.
  - Feel free - Signal is a completely independent 501c3 nonprofit.
  Development is supported by users like you. No advertisements. No trackers.
  No kidding.
  - Be yourself - You can use your existing phone number and address book to
  securely communicate with your friends.
  - Speak up - Whether they live across town or across the ocean, Signal's
  enhanced audio and video quality will make your friends and family feel
  closer.
  - Whisper in the shadows - Switch to the dark theme if you refuse to see
  the light.
  
  **Are you having issues?**
  
  Let us know by creating a new issue here:
  https://github.com/snapcrafters/signal-desktop/issues
  
  **Authors**
  
  This snap is maintained by the Snapcrafters community, and is not
  necessarily endorsed or officially maintained by the upstream developers.
commands:
  - signal-desktop
snap-id:      r4LxMVp7zWramXsJQAKdamxy6TAWlaDD
tracking:     latest/stable
refresh-date: today at 11:56 GMT
channels:
  latest/stable:    1.11.0 2023-11-23  (35) 137MB -
  latest/candidate: 6.39.1 2023-11-23 (556) 181MB -
  latest/beta:      ↑                             
  latest/edge:      ↑                             
installed:          1.11.0             (35) 137MB -
```

### Output of `snap connections $snap_name`

```shell
Interface        Plug                            Slot              Notes
browser-support  signal-desktop:browser-support  :browser-support  -
desktop          signal-desktop:desktop          :desktop          -
desktop-legacy   signal-desktop:desktop-legacy   :desktop-legacy   -
gsettings        signal-desktop:gsettings        :gsettings        -
home             signal-desktop:home             :home             -
network          signal-desktop:network          :network          -
opengl           signal-desktop:opengl           :opengl           -
pulseaudio       signal-desktop:pulseaudio       :pulseaudio       -
unity7           signal-desktop:unity7           :unity7           -
x11              signal-desktop:x11              :x11              -
```

### Output of `snap version`

```shell
12:07 ~ $ snap version
snap    2.60.4
snapd   2.60.4
series  16
ubuntu  22.04
kernel  5.15.0-88-generic
```

### Teminal output of app

```shell
see "what happened" above
```

**Comment by jooon** [comment]
Did someone just promote a really old version to stable?

```
latest/stable:    1.11.0 2023-11-23  (35) 137MB -
latest/candidate: 6.39.1 2023-11-23 (556) 181MB -
```

**Comment by stuartlangridge** [comment]
> Did someone just promote a really old version to stable?

Well, I can certainly confirm that `snap refresh --candidate signal-desktop` fixes it, so... it looks like that, maybe. I don't know whether this "1.11.0" version is very old (it doesn't look very old, UI-wise) or some other version or fork or something, but it doesn't work :)

**Comment by popey** [comment]
Thanks for filing the issue. Sorry this happened. Not quite how this occurred. I have just (re)pushed revision 554 to stable which is the revision you would have previously been on. My current theory is something went awry with a github action. Will investigate.

**Comment by popey** [comment]
I believe it's this: https://github.com/snapcrafters/signal-desktop/issues/201#issuecomment-1824076161 which triggered the problem.

**Comment by popey** [comment]
Going to close this as the revision that was promoted has been replaced with the correct revision. Will open a separate issue for why the GH action erroneously suggested to promote an old issue.
