### ISSUE TITLE
[Bug]: Candidate version (7.5.0) crashes on startup on amd64

### ISSUE THREAD

**Issue by lengau** [snapcrafters/signal-desktop#280]
### What happened?

On startup I get this error:

```
Unhandled Promise Rejection

Error: ENOENT, _locales/en/messages.json not found in [REDACTED]
    at createError (node:electron/js2c/node_init:2:1657)
    at t.readFileSync (node:electron/js2c/node_init:2:9941)
    at getLocaleMessages ([REDACTED]/app/locale.js:49:48)
    at load ([REDACTED]/app/locale.js:129:33)
    at App.<anonymous> ([REDACTED]/app/main.js:1351:57)
```

### What should have happened?

Start up normally

### Output of `snap info $snap_name`

```shell
lengau@ratel:~$ snap info signal-desktop
name:      signal-desktop
summary:   Speak Freely - Private Messenger
publisher: Snapcrafters✪
store-url: https://snapcraft.io/signal-desktop
contact:   https://github.com//snapcrafters/signal-desktop/issues
license:   AGPL-3.0-only
description: |
<snip>
commands:
  - signal-desktop
snap-id:      r4LxMVp7zWramXsJQAKdamxy6TAWlaDD
tracking:     latest/candidate
refresh-date: today at 13:18 EDT
channels:
  latest/stable:    7.4.0 2024-03-29 (642) 195MB -
  latest/candidate: 7.5.0 2024-04-17 (644) 190MB -
  latest/beta:      ↑                            
  latest/edge:      ↑                            
installed:          7.5.0            (644) 190MB -
```

### Output of `snap connections $snap_name`

```shell
lengau@ratel:~$ snap connections signal-desktop 
Interface               Plug                                   Slot                            Notes
audio-playback          signal-desktop:audio-playback          :audio-playback                 -
audio-record            signal-desktop:audio-record            :audio-record                   -
browser-support         signal-desktop:browser-support         :browser-support                -
camera                  signal-desktop:camera                  :camera                         -
content[gnome-42-2204]  signal-desktop:gnome-42-2204           gnome-42-2204:gnome-42-2204     -
content[gtk-3-themes]   signal-desktop:gtk-3-themes            gtk-common-themes:gtk-3-themes  -
content[icon-themes]    signal-desktop:icon-themes             gtk-common-themes:icon-themes   -
content[sound-themes]   signal-desktop:sound-themes            gtk-common-themes:sound-themes  -
desktop                 signal-desktop:desktop                 :desktop                        -
desktop-legacy          signal-desktop:desktop-legacy          :desktop-legacy                 -
gsettings               signal-desktop:gsettings               :gsettings                      -
home                    signal-desktop:home                    :home                           -
network                 signal-desktop:network                 :network                        -
opengl                  signal-desktop:opengl                  :opengl                         -
removable-media         signal-desktop:removable-media         -                               -
screen-inhibit-control  signal-desktop:screen-inhibit-control  :screen-inhibit-control         -
unity7                  signal-desktop:unity7                  :unity7                         -
wayland                 signal-desktop:wayland                 :wayland                        -
x11                     signal-desktop:x11                     :x11                            -
```

### Output of `snap version`

```shell
lengau@ratel:~$ snap version
snap    2.62+git2110.g5b5b54f
snapd   2.62+git2110.g5b5b54f
series  16
ubuntu  24.04
kernel  6.8.0-22-generic
```

### Teminal output of app

```shell
lengau@ratel:~$ signal-desktop 
Set Windows Application User Model ID (AUMID) { AUMID: 'org.whispersystems.signal-desktop' }
NODE_ENV production
NODE_CONFIG_DIR /snap/signal-desktop/644/opt/Signal/resources/app.asar/config
NODE_CONFIG {}
ALLOW_CONFIG_MUTATIONS undefined
HOSTNAME undefined
NODE_APP_INSTANCE undefined
SUPPRESS_NO_CONFIG_WARNING undefined
SIGNAL_ENABLE_HTTP undefined
userData: /home/lengau/snap/signal-desktop/644/.config/Signal
config/get: Successfully read user config file
config/get: Successfully read ephemeral config file
getLogger: Logger not yet initialized!
crashReporter: enabled
making app single instance
Error org.freedesktop.DBus.Error.Failed: cannot find desktop file "/var/lib/snapd/desktop/applications/signal-desktop_signal.desktop"
Error org.freedesktop.DBus.Error.Failed: cannot find desktop file "/var/lib/snapd/desktop/applications/signal-desktop_signal.desktop"

(signal-desktop:297517): Gtk-WARNING **: 13:39:14.035: Theme parsing error: gtk.css:1:21: Failed to import: Error opening file /home/lengau/snap/signal-desktop/644/.config/gtk-3.0/colors.css: No such file or directory
Gtk-Message: 13:39:14.053: Failed to load module "colorreload-gtk-module"
Gtk-Message: 13:39:14.053: Failed to load module "window-decorations-gtk-module"
Warning: build/dns-fallback.json not build, run `yarn generate`
/usr/share/libdrm/amdgpu.ids: No such file or directory
{"level":30,"time":"2024-04-17T17:39:14.110Z","msg":"crashReporter: enabled"}
{"level":30,"time":"2024-04-17T17:39:14.110Z","msg":"got fast localeOverride setting null"}
{"level":30,"time":"2024-04-17T17:39:14.110Z","msg":"app.ready: hour cycle preference: UnknownPreference"}
{"level":30,"time":"2024-04-17T17:39:14.110Z","msg":"app.ready: preferred system locales: en-GB, en"}
{"level":30,"time":"2024-04-17T17:39:14.111Z","msg":"locale: Supported locales: af-ZA, ar, az-AZ, bg-BG, bn-BD, bs-BA, ca, cs, da, de, el, en, es, et-EE, eu, fa-IR, fi, fr, ga-IE, gl-ES, gu-IN, he, hi-IN, hr-HR, hu, id, it, ja, ka-GE, kk-KZ, km-KH, kn-IN, ko, ky-KG, lt-LT, lv-LV, mk-MK, ml-IN, mr-IN, ms, my, nb, nl, pa-IN, pl, pt-BR, pt-PT, ro-RO, ru, sk-SK, sl-SI, sq-AL, sr, sv, sw, ta-IN, te-IN, th, tl-PH, tr, ug, uk-UA, ur, vi, yue, zh-CN, zh-HK, zh-Hant"}
{"level":30,"time":"2024-04-17T17:39:14.111Z","msg":"locale: Preferred locales: en-GB, en"}
{"level":30,"time":"2024-04-17T17:39:14.111Z","msg":"locale: Locale Override: null"}
{"level":30,"time":"2024-04-17T17:39:14.112Z","msg":"locale: Matched locale: en"}
Unhandled Promise Rejection: Error: ENOENT, _locales/en/messages.json not found in /snap/signal-desktop/644/opt/Signal/resources/app.asar
    at createError (node:electron/js2c/node_init:2:1657)
    at t.readFileSync (node:electron/js2c/node_init:2:9941)
    at getLocaleMessages (/snap/signal-desktop/644/opt/Signal/resources/app.asar/app/locale.js:49:48)
    at load (/snap/signal-desktop/644/opt/Signal/resources/app.asar/app/locale.js:129:33)
    at App.<anonymous> (/snap/signal-desktop/644/opt/Signal/resources/app.asar/app/main.js:1351:57)
{"level":50,"time":"2024-04-17T17:39:14.112Z","msg":"Unhandled Promise Rejection: Error: ENOENT, _locales/en/messages.json not found in [REDACTED]\n    at createError (node:electron/js2c/node_init:2:1657)\n    at t.readFileSync (node:electron/js2c/node_init:2:9941)\n    at getLocaleMessages ([REDACTED]/app/locale.js:49:48)\n    at load ([REDACTED]/app/locale.js:129:33)\n    at App.<anonymous> ([REDACTED]/app/main.js:1351:57)"}
/usr/share/libdrm/amdgpu.ids: No such file or directory
{"level":30,"time":"2024-04-17T17:39:16.808Z","msg":"quit event {\"hasEventBeenPrevented\":false,\"windowCount\":0,\"mainWindowExists\":false}"}
{"level":30,"time":"2024-04-17T17:39:16.809Z","msg":"MainSQL: updateSchema:\n  Current user_version: 1010;\n  Most recent db schema: 1010;\n  SQLite version: 3.42.0;\n  SQLCipher version: 4.5.5 community;\n  (deprecated) schema_version: 442;\n"}
```

**Comment by lengau** [comment]
Between this and the arm64 build timing out, I've decided to [manually re-run the release](https://github.com/snapcrafters/signal-desktop/actions/runs/8726352802) and see what happens.

**Comment by lengau** [comment]
arm64 build actually failed and the new release didn't fix it. Leaving this as unassigned since I don't have time to look at it right now

**Comment by jnsgruk** [comment]
Weird, a new release dropped yesterday, so I've kicked off that build to see if that fixes the issue: https://github.com/snapcrafters/signal-desktop/actions/runs/8749836707
