### ISSUE TITLE
[Bug]: cant start/database corrupted?

### ISSUE THREAD

**Issue by agrrr3** [snapcrafters/signal-desktop#331]
### What happened?

Got an error on starting the snap today after a reboot on my Kubuntu 24.04/wayland  (manually typed; it offered me to copy the error in an x window; wasnt able to copy-and-paste it though):

Datenbankfehler
Zugriff auf den Schlüssel zur Verschlüsselung der Datenbank ist nicht möglich, da das Verschlüsselungs-Keyring-Backend von kwallet5 zu basic_text geändert wurde. Dies kann auftreten, wenn sich die Desktop-Umgebung ändert, zum Beispiel von GNOME zu KDE.
...

I did not change the desktop environment. The snap claims it was refreshed 7 days ago; i think  i successfully restarted the laptop and the signal-desktop snap inbetween.

Note that there was a similar issue in the signal flatpak not long ago; not sure it is related

### What should have happened?

It should have opened the signal desktop app with my account and old conversations opened.

### Output of `snap info $snap_name`

```shell
snap-id:      r4LxMVp7zWramXsJQAKdamxy6TAWlaDD
tracking:     latest/stable
refresh-date: vor 7 Tagen, um 14:54 CEST
channels:
  latest/stable:    7.29.0 2024-10-17 (720) 183MB -
  latest/candidate: 7.29.0 2024-10-17 (720) 183MB -
  latest/beta:      ↑                             
  latest/edge:      ↑                             
installed:          7.29.0            (720) 183MB -
```

### Output of `snap connections $snap_name`

```shell
Schnittstelle           Plug                                   Slot                            Notizen
audio-playback          signal-desktop:audio-playback          :audio-playback                 -
audio-record            signal-desktop:audio-record            :audio-record                   -
browser-support         signal-desktop:browser-support         :browser-support                -
camera                  signal-desktop:camera                  -                               -
content[gnome-46-2404]  signal-desktop:gnome-46-2404           gnome-46-2404:gnome-46-2404     -
content[gpu-2404]       signal-desktop:gpu-2404                mesa-2404:gpu-2404              -
content[gtk-3-themes]   signal-desktop:gtk-3-themes            gtk-common-themes:gtk-3-themes  -
content[icon-themes]    signal-desktop:icon-themes             gtk-common-themes:icon-themes   -
content[sound-themes]   signal-desktop:sound-themes            gtk-common-themes:sound-themes  -
desktop                 signal-desktop:desktop                 :desktop                        -
desktop-legacy          signal-desktop:desktop-legacy          :desktop-legacy                 -
gsettings               signal-desktop:gsettings               :gsettings                      -
home                    signal-desktop:home                    -                               -
network                 signal-desktop:network                 :network                        -
opengl                  signal-desktop:opengl                  :opengl                         -
removable-media         signal-desktop:removable-media         -                               -
screen-inhibit-control  signal-desktop:screen-inhibit-control  :screen-inhibit-control         -
unity7                  signal-desktop:unity7                  :unity7                         -
wayland                 signal-desktop:wayland                 :wayland                        -
x11                     signal-desktop:x11                     -                               -
```

### Output of `snap version`

```shell
snap    2.65.3+24.04
snapd   2.65.3+24.04
series  16
ubuntu  24.04
kernel  6.8.0-47-generic
```

### Relevant log output

```shell
[47113.329081] audit: type=1400 audit(1729765298.698:1439): apparmor="DENIED" operation="open" class="file" profile="snap-update-ns.signal-desktop" name="/proc/93737/maps" pid=93737 comm="5" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
[47133.188144] audit: type=1400 audit(1729765318.557:1443): apparmor="DENIED" operation="file_perm" class="file" profile="snap.signal-desktop.signal-desktop" name="/run/user/1000/snap.signal-desktop/scoped_dir2RC0ux/SingletonSocket" pid=93714 comm="signal-desktop" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
[47133.188166] audit: type=1400 audit(1729765318.557:1444): apparmor="DENIED" operation="file_perm" class="file" profile="snap.signal-desktop.signal-desktop" name="/run/user/1000/snap.signal-desktop/scoped_dir2RC0ux/SingletonSocket" pid=93714 comm="signal-desktop" requested_mask="r" denied_mask="r" fsuid=1000 ouid=0
[47133.194544] audit: type=1400 audit(1729765318.563:1445): apparmor="DENIED" operation="open" class="file" profile="snap.signal-desktop.signal-desktop" name="/sys/fs/cgroup/user.slice/user-1000.slice/user@1000.service/app.slice/snap.signal-desktop.signal-desktop-4e9fb597-a9c8-43f1-8b67-d564816a28ef.scope/memory.max" pid=93714 comm="signal-desktop" requested_mask="r" denied_mask="r" fsuid=1000 ouid=1000
[47133.194578] audit: type=1400 audit(1729765318.563:1446): apparmor="DENIED" operation="open" class="file" profile="snap.signal-desktop.signal-desktop" name="/sys/fs/cgroup/user.slice/user-1000.slice/user@1000.service/app.slice/snap.signal-desktop.signal-desktop-4e9fb597-a9c8-43f1-8b67-d564816a28ef.scope/memory.high" pid=93714 comm="signal-desktop" requested_mask="r" denied_mask="r" fsuid=1000 ouid=1000
[47133.195147] audit: type=1400 audit(1729765318.564:1447): apparmor="DENIED" operation="open" class="file" profile="snap.signal-desktop.signal-desktop" name="/sys/fs/cgroup/user.slice/user-1000.slice/user@1000.service/app.slice/snap.signal-desktop.signal-desktop-4e9fb597-a9c8-43f1-8b67-d564816a28ef.scope/memory.max" pid=93714 comm="signal-desktop" requested_mask="r" denied_mask="r" fsuid=1000 ouid=1000
[47133.195186] audit: type=1400 audit(1729765318.564:1448): apparmor="DENIED" operation="open" class="file" profile="snap.signal-desktop.signal-desktop" name="/sys/fs/cgroup/user.slice/user-1000.slice/user@1000.service/app.slice/snap.signal-desktop.signal-desktop-4e9fb597-a9c8-43f1-8b67-d564816a28ef.scope/memory.high" pid=93714 comm="signal-desktop" requested_mask="r" denied_mask="r" fsuid=1000 ouid=1000
[47133.195827] audit: type=1400 audit(1729765318.565:1449): apparmor="DENIED" operation="open" class="file" profile="snap.signal-desktop.signal-desktop" name="/sys/fs/cgroup/user.slice/user-1000.slice/user@1000.service/app.slice/snap.signal-desktop.signal-desktop-4e9fb597-a9c8-43f1-8b67-d564816a28ef.scope/memory.max" pid=93714 comm="signal-desktop" requested_mask="r" denied_mask="r" fsuid=1000 ouid=1000
[47133.195871] audit: type=1400 audit(1729765318.565:1450): apparmor="DENIED" operation="open" class="file" profile="snap.signal-desktop.signal-desktop" name="/sys/fs/cgroup/user.slice/user-1000.slice/user@1000.service/app.slice/snap.signal-desktop.signal-desktop-4e9fb597-a9c8-43f1-8b67-d564816a28ef.scope/memory.high" pid=93714 comm="signal-desktop" requested_mask="r" denied_mask="r" fsuid=1000 ouid=1000
[47133.196361] audit: type=1400 audit(1729765318.565:1451): apparmor="DENIED" operation="open" class="file" profile="snap.signal-desktop.signal-desktop" name="/sys/fs/cgroup/user.slice/user-1000.slice/user@1000.service/app.slice/snap.signal-desktop.signal-desktop-4e9fb597-a9c8-43f1-8b67-d564816a28ef.scope/memory.max" pid=93714 comm="signal-desktop" requested_mask="r" denied_mask="r" fsuid=1000 ouid=1000
[47133.196393] audit: type=1400 audit(1729765318.565:1452): apparmor="DENIED" operation="open" class="file" profile="snap.signal-desktop.signal-desktop" name="/sys/fs/cgroup/user.slice/user-1000.slice/user@1000.service/app.slice/snap.signal-desktop.signal-desktop-4e9fb597-a9c8-43f1-8b67-d564816a28ef.scope/memory.high" pid=93714 comm="signal-desktop" requested_mask="r" denied_mask="r" fsuid=1000 ouid=1000
```

### Teminal output of app

```shell
Set Windows Application User Model ID (AUMID) { AUMID: 'org.whispersystems.signal-desktop' }
NODE_ENV production
NODE_CONFIG_DIR /snap/signal-desktop/720/opt/Signal/resources/app.asar/config
NODE_CONFIG {}
ALLOW_CONFIG_MUTATIONS undefined
HOSTNAME axel-T14s-Gen-1
NODE_APP_INSTANCE undefined
SUPPRESS_NO_CONFIG_WARNING undefined
SIGNAL_ENABLE_HTTP undefined
userData: /home/axel/snap/signal-desktop/720/.config/Signal
config/get: Successfully read user config file
config/get: Successfully read ephemeral config file
making app single instance
[93714:1024/122158.557817:ERROR:process_singleton_posix.cc(228)] read() failed: Permission denied (13)
[93714:1024/122158.558108:ERROR:process_singleton_posix.cc(1241)] Failed to extract pid from path: /home/axel/snap/signal-desktop/720/.config/Signal/SingletonLock
Error org.freedesktop.DBus.Error.Failed: cannot find desktop file "/var/lib/snapd/desktop/applications/signal-desktop_signal.desktop"
Error org.freedesktop.DBus.Error.Failed: cannot find desktop file "/var/lib/snapd/desktop/applications/signal-desktop_signal.desktop"

(signal-desktop:93714): Gtk-WARNING **: 12:21:58.787: Theme parsing error: gtk.css:1:21: Failed to import: Fehler beim Öffnen der Datei »/home/axel/snap/signal-desktop/720/.config/gtk-3.0/colors.css«: No such file or directory
Gtk-Message: 12:21:58.872: Failed to load module "colorreload-gtk-module"
Gtk-Message: 12:21:58.873: Failed to load module "window-decorations-gtk-module"
Gtk-Message: 12:21:58.873: Failed to load module "appmenu-gtk-module"
/usr/share/libdrm/amdgpu.ids: No such file or directory
/usr/share/libdrm/amdgpu.ids: No such file or directory
/usr/share/libdrm/amdgpu.ids: No such file or directory
{"level":30,"time":"2024-10-24T10:21:59.308Z","msg":"got fast localeOverride setting null"}
{"level":30,"time":"2024-10-24T10:21:59.310Z","msg":"app.ready: hour cycle preference: UnknownPreference"}
{"level":30,"time":"2024-10-24T10:21:59.310Z","msg":"app.ready: preferred system locales: de"}
{"level":30,"time":"2024-10-24T10:21:59.310Z","msg":"locale: Supported locales: af-ZA, ar, az-AZ, bg-BG, bn-BD, bs-BA, ca, cs, da, de, el, en, es, et-EE, eu, fa-IR, fi, fr, ga-IE, gl-ES, gu-IN, he, hi-IN, hr-HR, hu, id, it, ja, ka-GE, kk-KZ, km-KH, kn-IN, ko, ky-KG, lt-LT, lv-LV, mk-MK, ml-IN, mr-IN, ms, my, nb, nl, pa-IN, pl, pt-BR, pt-PT, ro-RO, ru, sk-SK, sl-SI, sq-AL, sr, sv, sw, ta-IN, te-IN, th, tl-PH, tr, ug, uk-UA, ur, vi, yue, zh-CN, zh-HK, zh-Hant"}
{"level":30,"time":"2024-10-24T10:21:59.311Z","msg":"locale: Preferred locales: de"}
{"level":30,"time":"2024-10-24T10:21:59.311Z","msg":"locale: Locale Override: null"}
{"level":30,"time":"2024-10-24T10:21:59.314Z","msg":"locale: Matched locale: de"}
{"level":40,"time":"2024-10-24T10:21:59.376Z","msg":"intl.onWarn [@formatjs/intl] \"defaultRichTextElements\" was specified but \"message\" was not pre-compiled. \nPlease consider using \"@formatjs/cli\" to pre-compile your messages for performance.\nFor more details see https://formatjs.io/docs/getting-started/message-distribution"}
{"level":30,"time":"2024-10-24T10:21:59.377Z","msg":"locale: Text info direction for de: ltr"}
{"level":50,"time":"2024-10-24T10:21:59.378Z","msg":"Detected change in safeStorage backend, can't decrypt DB key (previous: kwallet5, current: basic_text)"}
{"level":30,"time":"2024-10-24T10:21:59.379Z","msg":"getSystemTraySetting got value DoNotUseSystemTray"}
{"level":30,"time":"2024-10-24T10:21:59.379Z","msg":"getSystemTraySetting returning DoNotUseSystemTray"}
{"level":30,"time":"2024-10-24T10:21:59.382Z","msg":"app ready"}
{"level":30,"time":"2024-10-24T10:21:59.383Z","msg":"starting version 7.29.0"}
{"level":30,"time":"2024-10-24T10:21:59.383Z","msg":"media access status [object Undefined] [object Undefined]"}
{"level":30,"time":"2024-10-24T10:21:59.388Z","msg":"got fast theme-setting value system"}
{"level":30,"time":"2024-10-24T10:21:59.405Z","msg":"got fast theme-setting value system"}
{"level":30,"time":"2024-10-24T10:21:59.406Z","msg":"got fast spellcheck setting true"}
{"level":30,"time":"2024-10-24T10:21:59.407Z","msg":"visibleOnAnyScreen(window): x=723, y=83, width=960, height=953"}
{"level":30,"time":"2024-10-24T10:21:59.407Z","msg":"visibleOnAnyScreen(display #33): x=0, y=0, width=1920, height=1080"}
{"level":30,"time":"2024-10-24T10:21:59.407Z","msg":"Initializing BrowserWindow config: {\"show\":false,\"width\":960,\"height\":953,\"minWidth\":300,\"minHeight\":200,\"autoHideMenuBar\":false,\"titleBarStyle\":\"default\",\"backgroundColor\":\"#3a76f0\",\"webPreferences\":{\"devTools\":false,\"spellcheck\":true,\"enableBlinkFeatures\":\"CSSPseudoDir,CSSLogical\",\"enablePreferredSizeMode\":true,\"nodeIntegration\":false,\"nodeIntegrationInWorker\":false,\"sandbox\":false,\"contextIsolation\":true,\"preload\":\"[REDACTED]/preload.wrapper.js\",\"backgroundThrottling\":true,\"disableBlinkFeatures\":\"Accelerated2dCanvas,AcceleratedSmallCanvases\"},\"icon\":\"[REDACTED]/images/signal-logo-desktop-linux.png\",\"x\":723,\"y\":83}"}
{"level":30,"time":"2024-10-24T10:21:59.482Z","msg":"spellcheck: user locales: [\"de\"]"}
{"level":30,"time":"2024-10-24T10:21:59.482Z","msg":"spellcheck: available spellchecker languages: [\"af\",\"bg\",\"ca\",\"cs\",\"cy\",\"da\",\"de\",\"de-DE\",\"el\",\"en\",\"en-AU\",\"en-CA\",\"en-GB\",\"en-GB-oxendict\",\"en-US\",\"es\",\"es-419\",\"es-AR\",\"es-ES\",\"es-MX\",\"es-US\",\"et\",\"fa\",\"fo\",\"fr\",\"fr-FR\",\"he\",\"hi\",\"hr\",\"hu\",\"hy\",\"id\",\"it\",\"it-IT\",\"ko\",\"lt\",\"lv\",\"nb\",\"nl\",\"pl\",\"pt\",\"pt-BR\",\"pt-PT\",\"ro\",\"ru\",\"sh\",\"sk\",\"sl\",\"sq\",\"sr\",\"sv\",\"ta\",\"tg\",\"tr\",\"uk\",\"vi\"]"}
{"level":30,"time":"2024-10-24T10:21:59.482Z","msg":"spellcheck: setting languages to: [\"de\"]"}
[93714:1024/122159.485486:ERROR:object_proxy.cc(576)] Failed to call method: org.freedesktop.login1.Manager.Inhibit: object_path= /org/freedesktop/login1: org.freedesktop.DBus.Error.AccessDenied: An AppArmor policy prevents this sender from sending this message to this recipient; type="method_call", sender=":1.1353" (uid=1000 pid=93714 comm="/snap/signal-desktop/720/opt/Signal/signal-desktop" label="snap.signal-desktop.signal-desktop (enforce)") interface="org.freedesktop.login1.Manager" member="Inhibit" error name="(unset)" requested_reply="0" destination="org.freedesktop.login1" (uid=0 pid=2348 comm="/usr/lib/systemd/systemd-logind" label="unconfined")
2024-10-24 12:21:59.755: ERROR CORE sqlcipher_page_cipher: hmac check failed for pgno=1
2024-10-24 12:21:59.755: ERROR CORE sqlite3Codec: error decrypting page 1 data: 1
2024-10-24 12:21:59.755: ERROR CORE sqlcipher_codec_ctx_set_error 1
{"level":40,"time":"2024-10-24T10:21:59.756Z","msg":"MainSQL: Database log code=26: file is not a database in \"PRAGMA journal_mode = WAL\""}
{"level":30,"time":"2024-10-24T10:21:59.756Z","msg":"MainSQL: migrateDatabase: Migration without cipher change failed"}
2024-10-24 12:21:59.826: ERROR CORE sqlcipher_page_cipher: hmac check failed for pgno=1
2024-10-24 12:21:59.826: ERROR CORE sqlite3Codec: error decrypting page 1 data: 1
2024-10-24 12:21:59.826: ERROR CORE sqlcipher_codec_ctx_set_error 1
{"level":40,"time":"2024-10-24T10:21:59.827Z","msg":"MainSQL: Database log code=26: statement aborts at 2: [PRAGMA user_version] file is not a database"}
{"level":50,"time":"2024-10-24T10:21:59.827Z","msg":"MainSQL: Database startup error: SqliteError: file is not a database\n    at Database.pragma ([REDACTED]/node_modules/@signalapp/better-sqlite3/lib/methods/pragma.js:11:31)\n    at getUserVersion ([REDACTED]/ts/sql/util.js:132:13)\n    at migrateSchemaVersion ([REDACTED]/ts/sql/Server.js:409:54)\n    at openAndMigrateDatabase ([REDACTED]/ts/sql/Server.js:441:5)\n    at openAndSetUpSQLCipher ([REDACTED]/ts/sql/Server.js:463:14)\n    at initialize ([REDACTED]/ts/sql/Server.js:510:10)\n    at MessagePort.<anonymous> ([REDACTED]/ts/sql/mainWorker.js:69:41)\n    at [nodejs.internal.kHybridDispatch] (node:internal/event_target:820:20)\n    at MessagePort.<anonymous> (node:internal/per_context/messageport:23:28)"}
{"level":50,"time":"2024-10-24T10:21:59.828Z","msg":"Failed to get zoom factor {\"name\":\"SqliteError\"}"}
{"level":30,"time":"2024-10-24T10:22:00.501Z","msg":"got fast theme-setting value system"}
{"level":50,"time":"2024-10-24T10:22:01.396Z","msg":"sql.initialize was unsuccessful; returning early"}
{"level":30,"time":"2024-10-24T10:22:01.396Z","msg":"close event {\"readyForShutdown\":false,\"shouldQuit\":false}"}
{"level":30,"time":"2024-10-24T10:22:01.397Z","msg":"maybeRequestCloseConfirmation: Checking to see if close confirmation is needed"}
{"level":50,"time":"2024-10-24T10:22:05.325Z","msg":"onDatabaseError: Quitting application"}
{"level":30,"time":"2024-10-24T10:22:05.327Z","msg":"main window closed event"}
{"level":30,"time":"2024-10-24T10:22:05.328Z","msg":"quit event {\"hasEventBeenPrevented\":false,\"windowCount\":0,\"mainWindowExists\":false}"}
{"level":50,"time":"2024-10-24T10:22:05.330Z","msg":"Error occurred in handler for 'sql-channel:read': {\"name\":\"SqliteError\"}"}
```

**Comment by agrrr3** [comment]
seems this is a duplicate of #300 
which should be fixed with revision 722
i tried this morning (on 722) and it did not work; i tried again now and it suddenly it does work again.
So i optimistically close this (and reopen in case the bug resurfaces).

edit note: it seems the DB was not corrupted/i did not need to reinstall; just a refresh and two restarts and it worked
