### ISSUE TITLE
[Bug]: ARM64 Crash on startup - Unhandled Error

### ISSUE THREAD

**Issue by ovi-vansid** [snapcrafters/signal-desktop#337]
### What happened?

When starting Signal desktop, the application crashes with the following output:

Unhandled Error: Error: /snap/signal-desktop/729/opt/Signal/resources/app.asar.unpacked/node_modules/@signalapp/ringrtc/build/linux/libringrtc-arm64.node: undefined symbol: pulse_rust_init
    at process.func [as dlopen] (node:electron/js2c/node_init:2:2559)
    at Module._extensions..node (node:internal/modules/cjs/loader:1602:18)
    at Object.func [as .node] (node:electron/js2c/node_init:2:2786)
    at Module.load (node:internal/modules/cjs/loader:1295:32)
    at Module._load (node:internal/modules/cjs/loader:1111:12)
    at c._load (node:electron/js2c/node_init:2:16955)
    at Module.require (node:internal/modules/cjs/loader:1318:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/snap/signal-desktop/729/opt/Signal/resources/app.asar/node_modules/@signalapp/ringrtc/dist/ringrtc/Native.js:33:19)
    at Module._compile (node:internal/modules/cjs/loader:1484:14)
 

### What should have happened?

Normally, the application should start and present the Signal application in a window.

### Output of `snap info $snap_name`

```shell
name:      signal-desktop
summary:   Speak Freely - Private Messenger
publisher: Snapcrafters✪
store-url: https://snapcraft.io/signal-desktop
contact:   https://github.com//snapcrafters/signal-desktop/issues
license:   AGPL-3.0-only
description: |
  **Note: To use the Signal desktop app, you must first install Signal on your phone.**
  
  Millions of people use Signal every day for free and instantaneous communication anywhere in the
  world. Send and receive high-fidelity messages, participate in HD voice/video calls, and explore a
  growing set of new features that help you stay connected. Signal's advanced privacy-preserving
  technology is always enabled, so you can focus on sharing the moments that matter with the people
  who matter to you.
  
  - Say anything - State-of-the-art end-to-end encryption (powered by the open source Signal
  Protocol™) keeps your conversations secure. Privacy isn't an optional mode; it's just the way that
  Signal works. Every message, every call, every time.
  - Go fast - Messages are delivered quickly and reliably, even on slow networks. Signal is
  optimized to operate in the most constrained environment possible.
  - Feel free - Signal is a completely independent 501c3 nonprofit. Development is supported by
  users like you. No advertisements. No trackers. No kidding.
  - Be yourself - You can use your existing phone number and address book to securely communicate
  with your friends.
  - Speak up - Whether they live across town or across the ocean, Signal's enhanced audio and video
  quality will make your friends and family feel closer.
  - Whisper in the shadows - Switch to the dark theme if you refuse to see the light.
  
  **Minimize to tray**
  
  Per the request of the Signal developers, this snap does not use the system tray by default. This
  is disabled by default per the request of the Signal developers, because system tray support is
  not stable. Set to `false`, Signal will stop when you close it and will not have a system tray
  icon. You can enable it by running the following command.
  
      snap set signal-desktop tray-icon=true
  
  
  **Are you having issues?**
  
  Let us know by creating a new issue here: https://github.com/snapcrafters/signal-desktop/issues
  
  **Authors**
  
  This snap is maintained by the Snapcrafters community, and is not necessarily endorsed or
  officially maintained by the upstream developers.
commands:
  - signal-desktop
snap-id:      r4LxMVp7zWramXsJQAKdamxy6TAWlaDD
tracking:     latest/stable
refresh-date: today at 18:01 EST
channels:
  latest/stable:    7.33.0 2024-11-14 (729) 179MB -
  latest/candidate: 7.33.0 2024-11-14 (729) 179MB -
  latest/beta:      ↑                             
  latest/edge:      ↑                             
installed:          7.33.0            (729) 179MB -
```

### Output of `snap connections $snap_name`

```shell
Interface               Plug                                   Slot                            Notes
audio-playback          signal-desktop:audio-playback          :audio-playback                 -
audio-record            signal-desktop:audio-record            :audio-record                   -
browser-support         signal-desktop:browser-support         :browser-support                -
camera                  signal-desktop:camera                  :camera                         -
content[gnome-46-2404]  signal-desktop:gnome-46-2404           gnome-46-2404:gnome-46-2404     -
content[gpu-2404]       signal-desktop:gpu-2404                mesa-2404:gpu-2404              -
content[gtk-3-themes]   signal-desktop:gtk-3-themes            gtk-common-themes:gtk-3-themes  -
content[icon-themes]    signal-desktop:icon-themes             gtk-common-themes:icon-themes   -
content[sound-themes]   signal-desktop:sound-themes            gtk-common-themes:sound-themes  -
desktop                 signal-desktop:desktop                 :desktop                        -
desktop-legacy          signal-desktop:desktop-legacy          :desktop-legacy                 -
gsettings               signal-desktop:gsettings               :gsettings                      -
home                    signal-desktop:home                    :home                           -
network                 signal-desktop:network                 :network                        -
opengl                  signal-desktop:opengl                  :opengl                         -
removable-media         signal-desktop:removable-media         -                               -
screen-inhibit-control  signal-desktop:screen-inhibit-control  :screen-inhibit-control         -
unity7                  signal-desktop:unity7                  :unity7                         -
wayland                 signal-desktop:wayland                 :wayland                        -
x11                     signal-desktop:x11                     :x11                            -
```

### Output of `snap version`

```shell
snap    2.63
snapd   2.63
series  16
debian  12
kernel  6.6.51+rpt-rpi-2712
```

### Teminal output of app

```shell
[97335:1114/181330.862488:ERROR:gbm_wrapper.cc(262)] Failed to export buffer to dma_buf: No such file or directory (2)
getLogger: Logger not yet initialized!
quit event {
  hasEventBeenPrevented: false,
  windowCount: 0,
  mainWindowExists: false,
  mainWindowIsFullScreen: undefined
}
Unhandled Error: Error: /snap/signal-desktop/729/opt/Signal/resources/app.asar.unpacked/node_modules/@signalapp/ringrtc/build/linux/libringrtc-arm64.node: undefined symbol: pulse_rust_init
    at process.func [as dlopen] (node:electron/js2c/node_init:2:2559)
    at Module._extensions..node (node:internal/modules/cjs/loader:1602:18)
    at Object.func [as .node] (node:electron/js2c/node_init:2:2786)
    at Module.load (node:internal/modules/cjs/loader:1295:32)
    at Module._load (node:internal/modules/cjs/loader:1111:12)
    at c._load (node:electron/js2c/node_init:2:16955)
    at Module.require (node:internal/modules/cjs/loader:1318:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/snap/signal-desktop/729/opt/Signal/resources/app.asar/node_modules/@signalapp/ringrtc/dist/ringrtc/Native.js:33:19)
    at Module._compile (node:internal/modules/cjs/loader:1484:14)
Unhandled Error: Error: /snap/signal-desktop/729/opt/Signal/resources/app.asar.unpacked/node_modules/@signalapp/ringrtc/build/linux/libringrtc-arm64.node: undefined symbol: pulse_rust_init
    at process.func [as dlopen] (node:electron/js2c/node_init:2:2559)
    at Module._extensions..node (node:internal/modules/cjs/loader:1602:18)
    at Object.func [as .node] (node:electron/js2c/node_init:2:2786)
    at Module.load (node:internal/modules/cjs/loader:1295:32)
    at Module._load (node:internal/modules/cjs/loader:1111:12)
    at c._load (node:electron/js2c/node_init:2:16955)
    at Module.require (node:internal/modules/cjs/loader:1318:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/snap/signal-desktop/729/opt/Signal/resources/app.asar/node_modules/@signalapp/ringrtc/dist/ringrtc/Native.js:33:19)
    at Module._compile (node:internal/modules/cjs/loader:1484:14)
Unhandled Error: Error: /snap/signal-desktop/729/opt/Signal/resources/app.asar.unpacked/node_modules/@signalapp/ringrtc/build/linux/libringrtc-arm64.node: undefined symbol: pulse_rust_init
    at process.func [as dlopen] (node:electron/js2c/node_init:2:2559)
    at Module._extensions..node (node:internal/modules/cjs/loader:1602:18)
    at Object.func [as .node] (node:electron/js2c/node_init:2:2786)
    at Module.load (node:internal/modules/cjs/loader:1295:32)
    at Module._load (node:internal/modules/cjs/loader:1111:12)
    at c._load (node:electron/js2c/node_init:2:16955)
    at Module.require (node:internal/modules/cjs/loader:1318:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/snap/signal-desktop/729/opt/Signal/resources/app.asar/node_modules/@signalapp/ringrtc/dist/ringrtc/Native.js:33:19)
    at Module._compile (node:internal/modules/cjs/loader:1484:14)
Unhandled Error: Error: /snap/signal-desktop/729/opt/Signal/resources/app.asar.unpacked/node_modules/@signalapp/ringrtc/build/linux/libringrtc-arm64.node: undefined symbol: pulse_rust_init
    at process.func [as dlopen] (node:electron/js2c/node_init:2:2559)
    at Module._extensions..node (node:internal/modules/cjs/loader:1602:18)
    at Object.func [as .node] (node:electron/js2c/node_init:2:2786)
    at Module.load (node:internal/modules/cjs/loader:1295:32)
    at Module._load (node:internal/modules/cjs/loader:1111:12)
    at c._load (node:electron/js2c/node_init:2:16955)
    at Module.require (node:internal/modules/cjs/loader:1318:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/snap/signal-desktop/729/opt/Signal/resources/app.asar/node_modules/@signalapp/ringrtc/dist/ringrtc/Native.js:33:19)
    at Module._compile (node:internal/modules/cjs/loader:1484:14)
Unhandled Error: Error: /snap/signal-desktop/729/opt/Signal/resources/app.asar.unpacked/node_modules/@signalapp/ringrtc/build/linux/libringrtc-arm64.node: undefined symbol: pulse_rust_init
    at process.func [as dlopen] (node:electron/js2c/node_init:2:2559)
    at Module._extensions..node (node:internal/modules/cjs/loader:1602:18)
    at Object.func [as .node] (node:electron/js2c/node_init:2:2786)
    at Module.load (node:internal/modules/cjs/loader:1295:32)
    at Module._load (node:internal/modules/cjs/loader:1111:12)
    at c._load (node:electron/js2c/node_init:2:16955)
    at Module.require (node:internal/modules/cjs/loader:1318:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/snap/signal-desktop/729/opt/Signal/resources/app.asar/node_modules/@signalapp/ringrtc/dist/ringrtc/Native.js:33:19)
    at Module._compile (node:internal/modules/cjs/loader:1484:14)
Unhandled Error: Error: /snap/signal-desktop/729/opt/Signal/resources/app.asar.unpacked/node_modules/@signalapp/ringrtc/build/linux/libringrtc-arm64.node: undefined symbol: pulse_rust_init
    at process.func [as dlopen] (node:electron/js2c/node_init:2:2559)
    at Module._extensions..node (node:internal/modules/cjs/loader:1602:18)
    at Object.func [as .node] (node:electron/js2c/node_init:2:2786)
    at Module.load (node:internal/modules/cjs/loader:1295:32)
    at Module._load (node:internal/modules/cjs/loader:1111:12)
    at c._load (node:electron/js2c/node_init:2:16955)
    at Module.require (node:internal/modules/cjs/loader:1318:19)
    at require (node:internal/modules/helpers:179:18)
    at Object.<anonymous> (/snap/signal-desktop/729/opt/Signal/resources/app.asar/node_modules/@signalapp/ringrtc/dist/ringrtc/Native.js:33:19)
    at Module._compile (node:internal/modules/cjs/loader:1484:14)
```

**Comment by jnsgruk** [comment]
Hi, was this a fresh install, or was it working before an update? If so can you try a `snap revert signal-desktop`?

**Comment by ovi-vansid** [comment]
> Hi, was this a fresh install, or was it working before an update? If so can you try a `snap revert signal-desktop`?

This was an upgrade from the previous version, which was working normally.  I reverted to the previous version (7.32.0) and it seems to be working, so definitely something in the upgraded snap.

**Comment by jnsgruk** [comment]
Looks like this is a known upstream issue which should be fixed in the next desktop release: https://github.com/signalapp/ringrtc/issues/59

I'll remove the broken revision from the channel and wait for the next upstream release.

Keep an eye out for "call for testing" issues on this report if you're keen to help verify the fix! Thank you!

**Comment by mutexlox-signal** [comment]
(Note, in terms of marking releases as broken, that this should only affect ARM linux devices)

**Comment by jnsgruk** [comment]
@mutexlox-signal thanks! Indeed we were able to just yank the revision for arm64, amd64 is still on the latest version 😃

**Comment by ovi-vansid** [comment]
I upgraded my snap version to 7.34.0 and all is well.  No errors, seems to be working fine.  I think from the perspective of the Signal Desktop ARM64 snap, this can be closed/resolved.

**Comment by jnsgruk** [comment]
Great thanks!
