### ISSUE TITLE
Fails to link "Update Signal on this device to link your phone."

### ISSUE THREAD

**Issue by emiljoha** [snapcrafters/signal-desktop#43]
When Scanning the QR code with my android phone the app shows this error

![signal-errro](https://user-images.githubusercontent.com/12907343/94305445-78206e00-ff71-11ea-8b3a-cb6856b9468a.png)

Using the developer tools to look in the console I can see a lot of http errors 409 and 401. When scanning the QR code this error appear

```
background.js:1544 Uncaught (in promise) HTTPError: promiseAjax: error response; code: 401
    at makeHTTPError (/snap/signal-desktop/330/opt/Signal/resources/app.asar/ts/textsecure/WebAPI.js:386:15)
    at /snap/signal-desktop/330/opt/Signal/resources/app.asar/ts/textsecure/WebAPI.js:350:24
Original stack:
Error
    at _outerAjax (/snap/signal-desktop/330/opt/Signal/resources/app.asar/ts/textsecure/WebAPI.js:381:21)
    at _ajax (/snap/signal-desktop/330/opt/Signal/resources/app.asar/ts/textsecure/WebAPI.js:523:20)
    at Object.getConfig (/snap/signal-desktop/330/opt/Signal/resources/app.asar/ts/textsecure/WebAPI.js:585:31)
    at Object.exports.refreshRemoteConfig (/snap/signal-desktop/330/opt/Signal/resources/app.asar/ts/RemoteConfig.js:32:36)
    at invokeFunc (/snap/signal-desktop/330/opt/Signal/resources/app.asar/node_modules/lodash/lodash.js:10359:23)
    at leadingEdge (/snap/signal-desktop/330/opt/Signal/resources/app.asar/node_modules/lodash/lodash.js:10369:26)
    at Object.debounced [as maybeRefreshRemoteConfig] (/snap/signal-desktop/330/opt/Signal/resources/app.asar/node_modules/lodash/lodash.js:10436:20)
    at Object.initRemoteConfig (/snap/signal-desktop/330/opt/Signal/resources/app.asar/ts/RemoteConfig.js:17:19)
    at file:///snap/signal-desktop/330/opt/Signal/resources/app.asar/js/background.js:607:32
```

Attatching the full log

[signal-logs.txt](https://github.com/snapcrafters/signal-desktop/files/5284801/signal-logs.txt)

**Comment by popey** [comment]
Thanks for reporting the issue, sorry for the delay in responding.
I am not able to reproduce this with the latest builds. Are you still seeing it?

**Comment by emiljoha** [comment]
> Are you still seeing it?

Tested it today ( latest/stable: 1.37.3 2020-11-05 (335)) and it seems to be solved! :partying_face:

**Comment by malcolmocean** [comment]
For future reference:

I got this and running `sudo apt install signal-desktop` said it was up-to-date, but then when I actually ran all the lines shown on signal.org (including the ones that add a new source) it found a new version and installed it (I also uninstalled the old version first, which might have helped).
