### ISSUE TITLE
Crash when closing on Ubuntu 18.04

### ISSUE THREAD

**Issue by Toover** [snapcrafters/signal-desktop#53]
Hello, I had the following crash when trying to quit Signal :
```
Unhandled Error

Error: EACCES: permission denied, open '/home/victor.paleologue/snap/signal-desktop/342/.config/Signal/ephemeral.json'
    at Object.openSync (fs.js:440:3)
    at Object.func [as openSync] (electron/js2c/asar.js:140:31)
    at Object.writeFileSync (fs.js:1265:35)
    at Object.set ([REDACTED]/app.asar/app/base_config.js:48:8)
    at BrowserWindow.captureAndSaveWindowStats ([REDACTED]/app.asar/main.js:369:21)
    at invokeFunc ([REDACTED]/app.asar/node_modules/lodash/lodash.js:10359:23)
    at trailingEdge ([REDACTED]/app.asar/node_modules/lodash/lodash.js:10408:18)
    at Timeout.timerExpired [as _onTimeout] ([REDACTED]/app.asar/node_modules/lodash/lodash.js:10396:18)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
```

**Comment by galgalesh** [comment]
This is possibly caused by signal updating while it's running. This is a bug on the `snapd` side. There is an experimental fix available. You can turn it on by running:

```bash
snap set core experimental.refresh-app-awareness=true
```

This will disable updates while the app is running.

More information here: https://snapcraft.io/blog/experimental-feature-snap-refresh-awareness-and-update-inhibition

Please reopen the issue if this bug is still present with that workaround turned on.

**Comment by galgalesh** [comment]
note: duplicate of https://github.com/snapcrafters/signal-desktop/issues/8
